### ISSUE TITLE
loginWithUsernamePassword throwing error when logging in.

### ISSUE THREAD

**Issue by v-chtho5** [Azure/ms-rest-js#392]
**Package Version**: _______
- [x] **nodejs**
   - **nodejs version**:  11.x
   - **os name/version**:  Windows 10
- [x] **browser**
    - **name/version**: Chrome 83
**Describe the bug**

Running a snippet of code like so:
```
import { AzureMediaServices, LiveEvents, Locations, Mediaservices, StreamingEndpoints } from "@azure/arm-mediaservices";
import { LiveEvent, LiveEventsCreateOptionalParams, StreamingEndpoint, StreamingEndpointResourceState } from "@azure/arm-mediaservices/esm/models";
import { RequestOptionsBase } from "@azure/ms-rest-js";
import * as msRestNodeAuth from "@azure/ms-rest-nodeauth";

...
...

async login() {
        const data = this.data;
        this.credentials = await msRestNodeAuth.loginWithUsernamePassword(nconf.get("user"), nconf.get("pass"));
        this.ams = new AzureMediaServices(this.credentials, data.SubscriptionId, {});
    }
```
 I get an error on the login command, which also shows up as
`Error: Server returned error in RSTR - ErrorCode: NONE : FaultMessage: NONE`

as follows below:

```
Exception has occurred: Error
Error: Entry not found in cache.
    at Logger.createError (C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\adal-node\lib\log.js:216:13)
    at TokenRequest.<anonymous> (C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\adal-node\lib\token-request.js:526:40)
    at C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\adal-node\lib\token-request.js:148:20
    at C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\adal-node\lib\cache-driver.js:361:7
    at C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\adal-node\lib\cache-driver.js:231:5
    at C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\adal-node\lib\cache-driver.js:163:5
    at MemoryCache.find (C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\adal-node\lib\memory-cache.js:89:3)
    at CacheDriver._find (C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\adal-node\lib\cache-driver.js:140:15)
    at CacheDriver._getPotentialEntries (C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\adal-node\lib\cache-driver.js:161:8)
    at CacheDriver._loadSingleEntryFromCache (C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\adal-node\lib\cache-driver.js:194:8)
    at CacheDriver.find (C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\adal-node\lib\cache-driver.js:354:8)
    at TokenRequest._getTokenWithCacheWrapper (C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\adal-node\lib\token-request.js:140:21)
    at TokenRequest.getTokenFromCacheWithRefresh (C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\adal-node\lib\token-request.js:522:8)
    at AuthenticationContext.<anonymous> (C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\adal-node\lib\authentication-context.js:239:18)
    at C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\adal-node\lib\authentication-context.js:203:19
    at Authority._getOAuthEndpoints (C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\adal-node\lib\authority.js:238:5)
    at C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\adal-node\lib\authority.js:267:14
    at Authority._validateViaInstanceDiscovery (C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\adal-node\lib\authority.js:203:5)
    at Authority.validate (C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\adal-node\lib\authority.js:261:10)
    at AuthenticationContext._acquireToken (C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\adal-node\lib\authentication-context.js:198:19)
    at AuthenticationContext.acquireToken (C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\adal-node\lib\authentication-context.js:237:8)
    at Promise (c:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\@azure\ms-rest-nodeauth\lib\credentials\tokenCredentialsBase.ts:55:24)
    at new Promise (<anonymous>)
    at UserTokenCredentials.getTokenFromCache (c:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\@azure\ms-rest-nodeauth\lib\credentials\tokenCredentialsBase.ts:54:12)
    at UserTokenCredentials.<anonymous> (c:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\@azure\ms-rest-nodeauth\lib\credentials\userTokenCredentials.ts:74:25)
    at Generator.next (<anonymous>)
    at C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\@azure\ms-rest-nodeauth\dist\lib\credentials\userTokenCredentials.js:9:71
    at new Promise (<anonymous>)
    at __awaiter (C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\@azure\ms-rest-nodeauth\dist\lib\credentials\userTokenCredentials.js:5:12)
    at UserTokenCredentials.getToken (C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\@azure\ms-rest-nodeauth\dist\lib\credentials\userTokenCredentials.js:59:16)
    at c:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\@azure\ms-rest-nodeauth\lib\login.ts:176:15
    at Generator.next (<anonymous>)
    at C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\@azure\ms-rest-nodeauth\dist\lib\login.js:9:71
    at new Promise (<anonymous>)
    at __awaiter (C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\@azure\ms-rest-nodeauth\dist\lib\login.js:5:12)
    at withUsernamePasswordWithAuthResponse (C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\@azure\ms-rest-nodeauth\dist\lib\login.js:77:12)
    at Object.withUsernamePassword [as loginWithUsernamePassword] (c:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\@azure\ms-rest-nodeauth\lib\login.ts:764:12)
    at Connection.login (C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\Tests\Utils\SDKConnection.js:47:49)
    at Context.<anonymous> (C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\Tests\AccountCreateDeleteTest.js:52:26)
    at callFn (C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\mocha\lib\runnable.js:370:21)
    at Hook.Runnable.run (C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\mocha\lib\runnable.js:357:7)
    at next (C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\mocha\lib\runner.js:384:10)
    at Immediate._onImmediate (C:\OneBranchRepos\AAPT\Media\UX\src\TestSrc\e2etests\node_modules\mocha\lib\runner.js:428:5)
    at processImmediate (internal/timers.js:443:21)
```

**To Reproduce**
1. use a loginWithUsernamePassword() with private or microsoft account (over Microsoft VPN?)
2. it explod.

**Expected behavior**
I expect to be able to log in using this method and access the SDK to manipulate test accounts and resources for automation purposes.

**Additional context**
I'm trying to use some SDK automation to shorten integration testing for the Azure UX/Portal MEdia Services team, tying it in with msportalfx-test in Node.

**Comment by xirzec** [comment]
Seems like this belongs in https://github.com/Azure/ms-rest-nodeauth ?

**Comment by jeremymeng** [comment]
@v-chtho5 if this is still relevant, could you please log an issue in https://github.com/Azure/ms-rest-nodeauth repo instead?  Closing this.
